spring:
 profiles:
   active:
   -dev

---
spring:
  profiles: dev
    application:
     name: micro-weather-eureka-client-dev
---
spring:
  profiles: test
    application:
     name: micro-weather-eureka-client-test

